# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ipazzxyz/UniversalConverter

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ipazzxyz/UniversalConverter

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ipazzxyz/UniversalConverter/CMakeFiles /home/ipazzxyz/UniversalConverter//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ipazzxyz/UniversalConverter/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named UniversalConverter

# Build rule for target.
UniversalConverter: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 UniversalConverter
.PHONY : UniversalConverter

# fast build rule for target.
UniversalConverter/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UniversalConverter.dir/build.make CMakeFiles/UniversalConverter.dir/build
.PHONY : UniversalConverter/fast

#=============================================================================
# Target rules for targets named UniversalConverter_autogen_timestamp_deps

# Build rule for target.
UniversalConverter_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 UniversalConverter_autogen_timestamp_deps
.PHONY : UniversalConverter_autogen_timestamp_deps

# fast build rule for target.
UniversalConverter_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UniversalConverter_autogen_timestamp_deps.dir/build.make CMakeFiles/UniversalConverter_autogen_timestamp_deps.dir/build
.PHONY : UniversalConverter_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named UniversalConverter_autogen

# Build rule for target.
UniversalConverter_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 UniversalConverter_autogen
.PHONY : UniversalConverter_autogen

# fast build rule for target.
UniversalConverter_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UniversalConverter_autogen.dir/build.make CMakeFiles/UniversalConverter_autogen.dir/build
.PHONY : UniversalConverter_autogen/fast

UniversalConverter_autogen/mocs_compilation.o: UniversalConverter_autogen/mocs_compilation.cpp.o
.PHONY : UniversalConverter_autogen/mocs_compilation.o

# target to build an object file
UniversalConverter_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UniversalConverter.dir/build.make CMakeFiles/UniversalConverter.dir/UniversalConverter_autogen/mocs_compilation.cpp.o
.PHONY : UniversalConverter_autogen/mocs_compilation.cpp.o

UniversalConverter_autogen/mocs_compilation.i: UniversalConverter_autogen/mocs_compilation.cpp.i
.PHONY : UniversalConverter_autogen/mocs_compilation.i

# target to preprocess a source file
UniversalConverter_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UniversalConverter.dir/build.make CMakeFiles/UniversalConverter.dir/UniversalConverter_autogen/mocs_compilation.cpp.i
.PHONY : UniversalConverter_autogen/mocs_compilation.cpp.i

UniversalConverter_autogen/mocs_compilation.s: UniversalConverter_autogen/mocs_compilation.cpp.s
.PHONY : UniversalConverter_autogen/mocs_compilation.s

# target to generate assembly for a file
UniversalConverter_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UniversalConverter.dir/build.make CMakeFiles/UniversalConverter.dir/UniversalConverter_autogen/mocs_compilation.cpp.s
.PHONY : UniversalConverter_autogen/mocs_compilation.cpp.s

src/BigInt.o: src/BigInt.cpp.o
.PHONY : src/BigInt.o

# target to build an object file
src/BigInt.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UniversalConverter.dir/build.make CMakeFiles/UniversalConverter.dir/src/BigInt.cpp.o
.PHONY : src/BigInt.cpp.o

src/BigInt.i: src/BigInt.cpp.i
.PHONY : src/BigInt.i

# target to preprocess a source file
src/BigInt.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UniversalConverter.dir/build.make CMakeFiles/UniversalConverter.dir/src/BigInt.cpp.i
.PHONY : src/BigInt.cpp.i

src/BigInt.s: src/BigInt.cpp.s
.PHONY : src/BigInt.s

# target to generate assembly for a file
src/BigInt.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UniversalConverter.dir/build.make CMakeFiles/UniversalConverter.dir/src/BigInt.cpp.s
.PHONY : src/BigInt.cpp.s

src/Interface.o: src/Interface.cpp.o
.PHONY : src/Interface.o

# target to build an object file
src/Interface.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UniversalConverter.dir/build.make CMakeFiles/UniversalConverter.dir/src/Interface.cpp.o
.PHONY : src/Interface.cpp.o

src/Interface.i: src/Interface.cpp.i
.PHONY : src/Interface.i

# target to preprocess a source file
src/Interface.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UniversalConverter.dir/build.make CMakeFiles/UniversalConverter.dir/src/Interface.cpp.i
.PHONY : src/Interface.cpp.i

src/Interface.s: src/Interface.cpp.s
.PHONY : src/Interface.s

# target to generate assembly for a file
src/Interface.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UniversalConverter.dir/build.make CMakeFiles/UniversalConverter.dir/src/Interface.cpp.s
.PHONY : src/Interface.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UniversalConverter.dir/build.make CMakeFiles/UniversalConverter.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UniversalConverter.dir/build.make CMakeFiles/UniversalConverter.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UniversalConverter.dir/build.make CMakeFiles/UniversalConverter.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... UniversalConverter_autogen"
	@echo "... UniversalConverter_autogen_timestamp_deps"
	@echo "... UniversalConverter"
	@echo "... UniversalConverter_autogen/mocs_compilation.o"
	@echo "... UniversalConverter_autogen/mocs_compilation.i"
	@echo "... UniversalConverter_autogen/mocs_compilation.s"
	@echo "... src/BigInt.o"
	@echo "... src/BigInt.i"
	@echo "... src/BigInt.s"
	@echo "... src/Interface.o"
	@echo "... src/Interface.i"
	@echo "... src/Interface.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

